In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [18]:
music = pd.read_csv("spotify_millsongdata.csv")


In [5]:
music.head()

artist                   song                                        link  \
0   ABBA  Ahe's My Kind Of Girl  /a/abba/ahes+my+kind+of+girl_20598417.html   
1   ABBA       Andante, Andante       /a/abba/andante+andante_20002708.html   
2   ABBA         As Good As New        /a/abba/as+good+as+new_20003033.html   
3   ABBA                   Bang                  /a/abba/bang_20598415.html   
4   ABBA       Bang-A-Boomerang      /a/abba/bang+a+boomerang_20002668.html   

                                                text  
0  Look at her face, it's a wonderful face  \r\nA...  
1  Take it easy with me, please  \r\nTouch me gen...  
2  I'll never know why I had to go  \r\nWhy I had...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...

In [6]:
music.shape

(57650, 4)

In [7]:
music.columns

Index(['artist', 'song', 'link', 'text'], dtype='object')

In [8]:
music.describe()

artist                                    song  \
count          57650                                   57650   
unique           643                                   44824   
top     Donna Summer  Have Yourself A Merry Little Christmas   
freq             191                                      35   

                                              link  \
count                                        57650   
unique                                       57650   
top     /a/abba/ahes+my+kind+of+girl_20598417.html   
freq                                             1   

                                                     text  
count                                               57650  
unique                                              57494  
top     I just came back from a lovely trip along the ...  
freq                                                    6

In [9]:
music.head()

artist                   song                                        link  \
0   ABBA  Ahe's My Kind Of Girl  /a/abba/ahes+my+kind+of+girl_20598417.html   
1   ABBA       Andante, Andante       /a/abba/andante+andante_20002708.html   
2   ABBA         As Good As New        /a/abba/as+good+as+new_20003033.html   
3   ABBA                   Bang                  /a/abba/bang_20598415.html   
4   ABBA       Bang-A-Boomerang      /a/abba/bang+a+boomerang_20002668.html   

                                                text  
0  Look at her face, it's a wonderful face  \r\nA...  
1  Take it easy with me, please  \r\nTouch me gen...  
2  I'll never know why I had to go  \r\nWhy I had...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...

In [12]:
music['artist'].value_counts()

artist
Donna Summer        191
Gordon Lightfoot    189
Bob Dylan           188
George Strait       188
Loretta Lynn        187
                   ... 
Zazie                 2
Zed                   1
Zoe                   1
X-Treme               1
U-Kiss                1
Name: count, Length: 643, dtype: int64

In [13]:
music["song"].value_counts()

song
Have Yourself A Merry Little Christmas    35
Angel                                     28
Hold On                                   27
Home                                      27
I Believe                                 26
                                          ..
Just Be Good (Bushman Dub)                 1
Kingston Town                              1
Kiss And Say Goodbye                       1
Lambsbread                                 1
Generation                                 1
Name: count, Length: 44824, dtype: int64

In [22]:
# remove duplicates
df = music.drop_duplicates(inplace=True)

In [24]:
# Assuming 'music' is your DataFrame
music.drop_duplicates(inplace=True)


In [26]:
music["song"].value_counts()

song
Have Yourself A Merry Little Christmas    35
Angel                                     28
Hold On                                   27
Home                                      27
I Believe                                 26
                                          ..
Just Be Good (Bushman Dub)                 1
Kingston Town                              1
Kiss And Say Goodbye                       1
Lambsbread                                 1
Generation                                 1
Name: count, Length: 44824, dtype: int64

In [27]:
music_without_duplicates = music.drop_duplicates()


In [29]:
music_without_duplicates = music.drop_duplicates()
song_counts = music_without_duplicates["song"].value_counts()
print(song_counts)


song
Have Yourself A Merry Little Christmas    35
Angel                                     28
Hold On                                   27
Home                                      27
I Believe                                 26
                                          ..
Just Be Good (Bushman Dub)                 1
Kingston Town                              1
Kiss And Say Goodbye                       1
Lambsbread                                 1
Generation                                 1
Name: count, Length: 44824, dtype: int64


In [32]:
music.duplicated().sum()

0

In [34]:
# Handle artist 
music.iloc[0]["song"]

"Ahe's My Kind Of Girl"

In [35]:
import ast

def covert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name'])
    return L

In [42]:
music.head()

artist                   song                                        link  \
0   ABBA  Ahe's My Kind Of Girl  /a/abba/ahes+my+kind+of+girl_20598417.html   
1   ABBA       Andante, Andante       /a/abba/andante+andante_20002708.html   
2   ABBA         As Good As New        /a/abba/as+good+as+new_20003033.html   
3   ABBA                   Bang                  /a/abba/bang_20598415.html   
4   ABBA       Bang-A-Boomerang      /a/abba/bang+a+boomerang_20002668.html   

                                                text  
0  Look at her face, it's a wonderful face  \r\nA...  
1  Take it easy with me, please  \r\nTouch me gen...  
2  I'll never know why I had to go  \r\nWhy I had...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...

In [48]:
music.iloc[0]["text"]

"Look at her face, it's a wonderful face  \r\nAnd it means something special to me  \r\nLook at the way that she smiles when she sees me  \r\nHow lucky can one fellow be?  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?  \r\n  \r\nAnd when we go for a walk in the park  \r\nAnd she holds me and squeezes my hand  \r\nWe'll go on walking for hours and talking  \r\nAbout all the things that we plan  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"

In [50]:
# Now removing the space like that
def remove_space(L):
    L1 = []
    for i in ast.literal_eval(L):
        L1.append(i['name'].replace(" ",""))
    return L1

In [52]:
music["text"] = music["text"].apply(remove_space)

SyntaxError: invalid syntax (<unknown>, line 1)

In [53]:
new_df = music[["artist","song","text"]]

In [54]:
new_df.head()

artist                   song  \
0   ABBA  Ahe's My Kind Of Girl   
1   ABBA       Andante, Andante   
2   ABBA         As Good As New   
3   ABBA                   Bang   
4   ABBA       Bang-A-Boomerang   

                                                text  
0  Look at her face, it's a wonderful face  \r\nA...  
1  Take it easy with me, please  \r\nTouch me gen...  
2  I'll never know why I had to go  \r\nWhy I had...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...

In [55]:
# COnverting list to str
new_df["text"] = new_df["text"].apply(lambda x: str(x))

C:\Users\DELL\AppData\Local\Temp\ipykernel_6528\1663591845.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["text"] = new_df["text"].apply(lambda x: str(x))


In [56]:
new_df.head()

artist                   song  \
0   ABBA  Ahe's My Kind Of Girl   
1   ABBA       Andante, Andante   
2   ABBA         As Good As New   
3   ABBA                   Bang   
4   ABBA       Bang-A-Boomerang   

                                                text  
0  Look at her face, it's a wonderful face  \r\nA...  
1  Take it easy with me, please  \r\nTouch me gen...  
2  I'll never know why I had to go  \r\nWhy I had...  
3  Making somebody happy is a question of give an...  
4  Making somebody happy is a question of give an...

In [57]:
new_df.iloc[0]["text"]

"Look at her face, it's a wonderful face  \r\nAnd it means something special to me  \r\nLook at the way that she smiles when she sees me  \r\nHow lucky can one fellow be?  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?  \r\n  \r\nAnd when we go for a walk in the park  \r\nAnd she holds me and squeezes my hand  \r\nWe'll go on walking for hours and talking  \r\nAbout all the things that we plan  \r\n  \r\nShe's just my kind of girl, she makes me feel fine  \r\nWho could ever believe that she could be mine?  \r\nShe's just my kind of girl, without her I'm blue  \r\nAnd if she ever leaves me what could I do, what could I do?\r\n\r\n"

In [58]:
# Converting to lower case
new_df["text"] = new_df["text"].apply(lambda x: x.lower())
new_df.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_6528\3374669289.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["text"] = new_df["text"].apply(lambda x: x.lower())


artist                   song  \
0   ABBA  Ahe's My Kind Of Girl   
1   ABBA       Andante, Andante   
2   ABBA         As Good As New   
3   ABBA                   Bang   
4   ABBA       Bang-A-Boomerang   

                                                text  
0  look at her face, it's a wonderful face  \r\na...  
1  take it easy with me, please  \r\ntouch me gen...  
2  i'll never know why i had to go  \r\nwhy i had...  
3  making somebody happy is a question of give an...  
4  making somebody happy is a question of give an...

In [59]:
new_df.head()

artist                   song  \
0   ABBA  Ahe's My Kind Of Girl   
1   ABBA       Andante, Andante   
2   ABBA         As Good As New   
3   ABBA                   Bang   
4   ABBA       Bang-A-Boomerang   

                                                text  
0  look at her face, it's a wonderful face  \r\na...  
1  take it easy with me, please  \r\ntouch me gen...  
2  i'll never know why i had to go  \r\nwhy i had...  
3  making somebody happy is a question of give an...  
4  making somebody happy is a question of give an...

In [60]:
new_df.iloc[0]["text"]

"look at her face, it's a wonderful face  \r\nand it means something special to me  \r\nlook at the way that she smiles when she sees me  \r\nhow lucky can one fellow be?  \r\n  \r\nshe's just my kind of girl, she makes me feel fine  \r\nwho could ever believe that she could be mine?  \r\nshe's just my kind of girl, without her i'm blue  \r\nand if she ever leaves me what could i do, what could i do?  \r\n  \r\nand when we go for a walk in the park  \r\nand she holds me and squeezes my hand  \r\nwe'll go on walking for hours and talking  \r\nabout all the things that we plan  \r\n  \r\nshe's just my kind of girl, she makes me feel fine  \r\nwho could ever believe that she could be mine?  \r\nshe's just my kind of girl, without her i'm blue  \r\nand if she ever leaves me what could i do, what could i do?\r\n\r\n"

In [61]:
import nltk
from nltk.stem import PorterStemmer

In [62]:
ps = PorterStemmer()

In [65]:
def stems(text):
    T = []
    for i in text.split():
        T.append(ps.stem(i))
    return " ".join(T)


In [66]:
new_df["text"] = new_df["text"].apply(stems)

C:\Users\DELL\AppData\Local\Temp\ipykernel_6528\1691157402.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["text"] = new_df["text"].apply(stems)


In [67]:
new_df.iloc[0]["text"]

"look at her face, it' a wonder face and it mean someth special to me look at the way that she smile when she see me how lucki can one fellow be? she' just my kind of girl, she make me feel fine who could ever believ that she could be mine? she' just my kind of girl, without her i'm blue and if she ever leav me what could i do, what could i do? and when we go for a walk in the park and she hold me and squeez my hand we'll go on walk for hour and talk about all the thing that we plan she' just my kind of girl, she make me feel fine who could ever believ that she could be mine? she' just my kind of girl, without her i'm blue and if she ever leav me what could i do, what could i do?"

In [68]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words="english")

In [79]:
new_df = new_df.sample(10000)

In [80]:
vector = cv.fit_transform(new_df["text"]).toarray()

In [81]:
vector[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [82]:
vector.shape

(10000, 5000)

In [83]:
len(cv.get_feature_names_out())


5000

In [84]:
from sklearn.metrics.pairwise import cosine_similarity

In [86]:

similarity = cosine_similarity(vector)

In [87]:
# similarity
similarity.shape

(10000, 10000)

In [90]:
new_df.head()

artist              song  \
55972             Westlife   Everybody Knows   
40982        Kylie Minogue     Dancing Queen   
40428                Kinks  Have A Cuppa Tea   
51975              Squeeze  It's Not Cricket   
52415  Stone Temple Pilots   Ride The Cliche   

                                                    text  
55972  it' never too hard to find the word the word t...  
40982  you can dance, you can jive, have the time of ...  
40428  granny' alway ravin' and rantin' and she' alwa...  
51975  she use to do a topless down at the surrey doc...  
52415  she no wait but she know me intak purg it' my ...

In [91]:
# Check if there are any rows matching the condition
matching_rows = new_df[new_df["song"] == "Everybody Knows"]
if not matching_rows.empty:
    # Access the index of the first matching row
    index_of_first_matching_row = matching_rows.index[0]
    print("Index of the first matching row:", index_of_first_matching_row)
else:
    print("No rows found matching the condition.")


Index of the first matching row: 55972


In [101]:

def recommend(movie):
    index = new_df[new_df['song'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])),reverse=True,key = lambda x: x[1])
    for i in distances[1:6]:
        print(new_df.iloc[i[0]].song)

In [102]:
new_df.head()

artist              song  \
55972             Westlife   Everybody Knows   
40982        Kylie Minogue     Dancing Queen   
40428                Kinks  Have A Cuppa Tea   
51975              Squeeze  It's Not Cricket   
52415  Stone Temple Pilots   Ride The Cliche   

                                                    text  
55972  it' never too hard to find the word the word t...  
40982  you can dance, you can jive, have the time of ...  
40428  granny' alway ravin' and rantin' and she' alwa...  
51975  she use to do a topless down at the surrey doc...  
52415  she no wait but she know me intak purg it' my ...

## Training Model

In [107]:
from scipy.sparse import csr_matrix

In [108]:
# Let's create a pivot table
pivot_table = new_df.pivot_table(index='artist',columns='song',values='text',aggfunc='first')

In [109]:
pivot_table

song          '39 'Deed I Do 'Round And 'Round The Christmas Tree  \
artist                                                              
'n Sync       NaN        NaN                                  NaN   
ABBA          NaN        NaN                                  NaN   
Ace Of Base   NaN        NaN                                  NaN   
Adam Sandler  NaN        NaN                                  NaN   
Adele         NaN        NaN                                  NaN   
...           ...        ...                                  ...   
Zoegirl       NaN        NaN                                  NaN   
Zornik        NaN        NaN                                  NaN   
Zox           NaN        NaN                                  NaN   
Zucchero      NaN        NaN                                  NaN   
Zwan          NaN        NaN                                  NaN   

song         'a' Bomb In Wardour Street 'di Bale Na Lang  \
artist                                                     
'n Sync                             NaN              NaN   
ABBA                                NaN              NaN   
Ace Of Base                         NaN              NaN   
Adam Sandler                        NaN              NaN   
Adele                               NaN              NaN   
...                                 ...              ...   
Zoegirl                             NaN              NaN   
Zornik                              NaN              NaN   
Zox                                 NaN              NaN   
Zucchero                            NaN              NaN   
Zwan                                NaN              NaN   

song         'til You Come Back To Me 'til You Let Your Heart Win  \
artist                                                              
'n Sync                           NaN                         NaN   
ABBA                              NaN                         NaN   
Ace Of Base                       NaN                         NaN   
Adam Sandler                      NaN                         NaN   
Adele                             NaN                         NaN   
...                               ...                         ...   
Zoegirl                           NaN                         NaN   
Zornik                            NaN                         NaN   
Zox                               NaN                         NaN   
Zucchero                          NaN                         NaN   
Zwan                              NaN                         NaN   

song         'twas Tea-Time At The Circus (Ain't That) Just Like Me  \
artist                                                                
'n Sync                               NaN                       NaN   
ABBA                                  NaN                       NaN   
Ace Of Base                           NaN                       NaN   
Adam Sandler                          NaN                       NaN   
Adele                                 NaN                       NaN   
...                                   ...                       ...   
Zoegirl                               NaN                       NaN   
Zornik                                NaN                       NaN   
Zox                                   NaN                       NaN   
Zucchero                              NaN                       NaN   
Zwan                                  NaN                       NaN   

song         (Don't Fear) The Reaper  ... Youthanasia Yukon Railroad Z-Ro  \
artist                                ...                                   
'n Sync                          NaN  ...         NaN            NaN  NaN   
ABBA                             NaN  ...         NaN            NaN  NaN   
Ace Of Base                      NaN  ...         NaN            NaN  NaN   
Adam Sandler                     NaN  ...         NaN            NaN  NaN   
Adele                            NaN 

In [110]:
pivot_table.shape

(631, 9235)

In [111]:
pivot_table.fillna(0, inplace=True)

In [112]:
pivot_table

song         '39 'Deed I Do 'Round And 'Round The Christmas Tree  \
artist                                                             
'n Sync        0          0                                    0   
ABBA           0          0                                    0   
Ace Of Base    0          0                                    0   
Adam Sandler   0          0                                    0   
Adele          0          0                                    0   
...           ..        ...                                  ...   
Zoegirl        0          0                                    0   
Zornik         0          0                                    0   
Zox            0          0                                    0   
Zucchero       0          0                                    0   
Zwan           0          0                                    0   

song         'a' Bomb In Wardour Street 'di Bale Na Lang  \
artist                                                     
'n Sync                               0                0   
ABBA                                  0                0   
Ace Of Base                           0                0   
Adam Sandler                          0                0   
Adele                                 0                0   
...                                 ...              ...   
Zoegirl                               0                0   
Zornik                                0                0   
Zox                                   0                0   
Zucchero                              0                0   
Zwan                                  0                0   

song         'til You Come Back To Me 'til You Let Your Heart Win  \
artist                                                              
'n Sync                             0                           0   
ABBA                                0                           0   
Ace Of Base                         0                           0   
Adam Sandler                        0                           0   
Adele                               0                           0   
...                               ...                         ...   
Zoegirl                             0                           0   
Zornik                              0                           0   
Zox                                 0                           0   
Zucchero                            0                           0   
Zwan                                0                           0   

song         'twas Tea-Time At The Circus (Ain't That) Just Like Me  \
artist                                                                
'n Sync                                 0                         0   
ABBA                                    0                         0   
Ace Of Base                             0                         0   
Adam Sandler                            0                         0   
Adele                                   0                         0   
...                                   ...                       ...   
Zoegirl                                 0                         0   
Zornik                                  0                         0   
Zox                                     0                         0   
Zucchero                                0                         0   
Zwan                                    0                         0   

song         (Don't Fear) The Reaper  ... Youthanasia Yukon Railroad Z-Ro  \
artist                                ...                                   
'n Sync                            0  ...           0              0    0   
ABBA                               0  ...           0              0    0   
Ace Of Base                        0  ...           0              0    0   
Adam Sandler                       0  ...           0              0    0   
Adele                              0  ...         

In [117]:
import string
import re

def preprocess_text(text):
    # Convert text to lowercase
    text = text.lower()
    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text)
    return text


In [120]:
music['text'] = music['text'].apply(preprocess_text)


In [121]:
# Compute similarity
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(text_vectors)

In [126]:
music.head()

artist                   song                                        link  \
0   ABBA  Ahe's My Kind Of Girl  /a/abba/ahes+my+kind+of+girl_20598417.html   
1   ABBA       Andante, Andante       /a/abba/andante+andante_20002708.html   
2   ABBA         As Good As New        /a/abba/as+good+as+new_20003033.html   
3   ABBA                   Bang                  /a/abba/bang_20598415.html   
4   ABBA       Bang-A-Boomerang      /a/abba/bang+a+boomerang_20002668.html   

                                                text  
0  look at her face its a wonderful face and it m...  
1  take it easy with me please touch me gently li...  
2  ill never know why i had to go why i had to pu...  
3  making somebody happy is a question of give an...  
4  making somebody happy is a question of give an...

In [130]:
recommend("Ahe's My Kind Of Girl")

No matching song found for 'Ahe's My Kind Of Girl'


In [131]:
# Now import our clustering algoritms which is nearest Neighbors this is unsupervised algorithms
from sklearn.neighbors import NearestNeighbors

# Create the Nearest Neighbors model
model = NearestNeighbors(metric='cosine', algorithm='brute')
model.fit(text_vectors)

NearestNeighbors(algorithm='brute', metric='cosine')

In [155]:
# create distance and suggestion variable
distance, suggestion = [], []

for i in range(0, len(music)):
    distance.append(
        model.kneighbors(
            text_vectors[i].reshape(1, -1), n_neighbors=6
        )
    )
    suggestion.append(
        model.kneighbors(
            text_vectors[i].reshape(1, -1), n_neighbors=6
        )
    )
    

IndexError: row index (10000) out of range

In [ ]:
suggestion

[(array([[2.22044605e-16, 3.24145010e-01, 3.27643256e-01, 3.35842805e-01,
          3.39664314e-01, 3.43198863e-01]]),
  array([[   0, 6231, 7010, 6900, 7303, 4409]], dtype=int64)),
 (array([[1.11022302e-16, 1.45202263e-02, 2.70695405e-01, 2.72743610e-01,
          2.82094829e-01, 2.82723078e-01]]),
  array([[   1, 6659, 9852, 6034, 4410, 9328]], dtype=int64)),
 (array([[0.        , 0.52431575, 0.53175386, 0.53290104, 0.53932177,
          0.54045352]]),
  array([[   2, 5122, 6236,  857, 9645, 3186]], dtype=int64)),
 (array([[0.        , 0.33024503, 0.33301314, 0.33702936, 0.33900897,
          0.34000174]]),
  array([[   3, 4873, 9890, 8793, 3574, 5679]], dtype=int64)),
 (array([[0.        , 0.41267774, 0.41617215, 0.42255278, 0.42455969,
          0.42885657]]),
  array([[   4, 4350, 8369, 5982, 4156, 3178]], dtype=int64)),
 (array([[4.44089210e-16, 3.95900174e-01, 3.99583590e-01, 4.04965453e-01,
          4.28025431e-01, 4.31406860e-01]]),
  array([[   5, 6873, 9840,  213, 2267, 418